# Use a image you want tto use
FROM alpine

LABEL "name"="{{ cookiecutter.actions_name }}"
LABEL "maintainer"="{{ cookiecutter.user_name }} <{{ cookiecutter.user_email }}>"
LABEL "version"="0.0.0"

LABEL "com.github.actions.name"="{{ cookiecutter.actions_name }}"
LABEL "com.github.actions.description"="{{ cookiecutter.actions_description }}"
LABEL "com.github.actions.icon"="briefcase"
LABEL "com.github.actions.color"="blue"


#